% Produced by CVXGEN, 2023-09-05 15:37:09 -0400.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
G = params.G;
P = params.P;
h = params.h;
lb = params.lb;
q = params.q;
ub = params.ub;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable x(3, 1);

  minimize(0.5*quad_form(x, P) + q'*x);
  subject to
    G*x <= h;
    min(x) >= lb;
    max(x) <= ub;
cvx_end
vars.x = x;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
